export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000/api/v1";

export const endpoints = {
  auth: {
    csrf: "/auth/csrf/",
    login: "/auth/login/",
    logout: "/auth/logout/",
    me: "/auth/me/",
    changePassword: "/auth/change-password/",
  },
  system: {
    dashboard: "/system/dashboard/",
    health: "/system/health/",
    organizations: "/system/organizations/",
    organizationDetail: (orgId: string) => `/system/organizations/${orgId}/`,
    organizationAdmins: (orgId: string) => `/system/organizations/${orgId}/admins/`,
    audit: "/system/audit/",
  },
  org: {
    dashboard: "/org/dashboard/",
    settings: "/org/settings/",
    elections: "/org/elections/",
    electionDetail: (electionId: string) => `/org/elections/${electionId}/`,
    electionStatus: (electionId: string) => `/org/elections/${electionId}/status/`,
    electionDuplicate: (electionId: string) => `/org/elections/${electionId}/duplicate/`,
    posts: (electionId: string) => `/org/elections/${electionId}/posts/`,
    postDetail: (postId: string) => `/org/posts/${postId}/`,
    candidates: (postId: string) => `/org/posts/${postId}/candidates/`,
    candidateDetail: (candidateId: string) => `/org/candidates/${candidateId}/`,
    tokenBatches: (electionId: string) => `/org/elections/${electionId}/token-batches/`,
    usedTokens: (electionId: string, search?: string) =>
      `/org/elections/${electionId}/used-tokens/${search ? `?search=${encodeURIComponent(search)}` : ""}`,
    deleteBatch: (batchId: string) => `/org/token-batches/${batchId}/`,
    revokeBatch: (batchId: string) => `/org/token-batches/${batchId}/revoke/`,
    tokenBatchTokens: (batchId: string) => `/org/token-batches/${batchId}/tokens/`,
    resetTokenVote: (tokenId: string) => `/org/tokens/${tokenId}/reset-vote/`,
    deleteToken: (tokenId: string) => `/org/tokens/${tokenId}/`,
    tokenExportCsv: (batchId: string) => `/org/token-batches/${batchId}/export/csv/`,
    tokenExportPrint: (batchId: string) => `/org/token-batches/${batchId}/export/print/`,
    tokenExportQr: (batchId: string) => `/org/token-batches/${batchId}/export/qr/`,
    tokenExportQrPrint: (batchId: string) => `/org/token-batches/${batchId}/export/qr-print/`,
    results: (electionId: string) => `/org/elections/${electionId}/results/`,
    publishResults: (electionId: string) => `/org/elections/${electionId}/publish-results/`,
    exportExcel: (electionId: string) => `/org/elections/${electionId}/export/excel/`,
    users: "/org/users/",
    userDetail: (membershipId: string) => `/org/users/${membershipId}/`,
    audit: "/org/audit/",
  },
  vote: {
    tokenLogin: "/vote/token-login/",
    logout: "/vote/logout/",
    ballot: (slug: string) => `/vote/elections/${slug}/ballot/`,
    submit: (slug: string) => `/vote/elections/${slug}/submit/`,
    status: (slug: string) => `/vote/elections/${slug}/status/`,
    results: (slug: string) => `/vote/elections/${slug}/results/`,
  },
};
